version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SmallReminders"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fb7qmpbx11yg"
s3_prefix = "SmallReminders"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
